sveltejs/svelte-loader

package.json
This allows developers to install svelte-loader from npm
while having full control over the actual version being used.
=> Fix: Depend on svelte as a peerDependency

example/package.json
1.0.1 made svelte a peerDependency to svelte-loader. This pull request just adds svelte as a dependency to the example.
=> Added svelte as a dependency to the example

index.js, package.json, test/loader.spec.js
Hello,
This would be really helpful since for many use cases we will need UMD, or CommonJS, ... in our webpack toolchain.
=> Add options to control the output format

index.js, test/loader.spec.js
Adding the location and frame information to error logging information. Currently with the webpack devserver only the filename and type of error is output. This adds location and context to the output.
=> Adding more error information

README.md, index.js, package-lock.json, package.json, test/loader.spec.js
Hey there!
I added support for emitting the CSS as separate modules. The idea is to create temporary files containing the css output and altering the compiled code to require the temp files. This approach has the advantage that the resulting css modules are handled by webpack just as regular files, so the configured rules and plugins apply as normal. This way you can chain postcss-loader or extract the css as a separate output file, using the ExtractTextPlugin: 
```
module: {
rules: [
{
test: /\.(html|js)$/,
exclude: /node_modules/,
use: {
loader: 'babel-loader',
options: {
presets: [
[
'env',
{
targets: {
ie: '11',
browsers: ['last 2 versions'],
},
modules: false,
useBuiltIns: true,
},
],
],
},
},
},
{
test: /\.html$/,
exclude: /node_modules/,
use: {
loader: 'svelte-loader',
options: { …
```
=> Add emitCss option

index.js
I have read over the thread you mentioned on my previous pull request (https://github.com/webpack/watchpack/issues/25) and It struck me that there is another issue with the current implementation:
> Normally multiple rebuilds shouldn't cause issues and this cause should be cached by the caller by comparing hash. I.e. the webpack CLI doesn't display stats output for equal hash.
If you run webpack multiple times over the same Svelte file, the output hash is different each time. If you take out the <style> tag, then the hash remains the same. This happens because a new temporary css file with a random name is generated each time. This could prove annoying to developers using code splitting or relying on output files including [hash] …
=> (fix) emitCss: use deterministic css file names

.gitignore, .travis.yml, index.js, package-lock.json, package.json, test/fixtures/style-valid.html, test/loader.spec.js
Utilized `svelte.preprocess` introduced to svelte in v1.44.0
=> Preprocessing

index.js
This seems to be necessary in at least some Node versions, and/or some versions of Windows.
=> wrap utimes arguments in new Date()

index.js
Using the full local path exposes security/privacy issues when svelte components are provided as NPM modules. The compiled code includes the path information in the variable names. This also bloats the code, which isn't as much an issue since it eventually gets compressed with libraries such as uglify. The bigger issue is the local path information being publicized this way.
Are there any issues with removing `require.resolve`? Svelte should be available without it, but perhaps there are edge cases I cannot think of.
See https://github.com/sveltejs/svelte-loader/issues/29
=> Don't resolve the shared.js to the full local path

index.js
Webpack on Windows (wow!) doesn't appear to like absolute paths with `\` characters in them — it expects everything to use forward slashes. No idea why. But this seems like a plausible fix.
=> posixify tmp css paths, for sake of windows

index.js
The Pull Request https://github.com/sveltejs/svelte-loader/pull/34 introduced `posix.join` to fix Windows paths but this doesn't convert the path separators returned from `tmpdir` to be `/` slashes. I think this results in webpack having paths with escaped characters. 
This path is the result of `posix.join(tmpdir(), 'svelte-12415.css')`
`C:\Users\Bryan\AppData\Local\Temp/svelte-12415.css` 
webpack reports an error finding a module with this path
`C:UsersBryanAppDataLocalTemp/svelte-12415.css`. 
This PR replaces the `\` with `/` to make it posix style.
Node Version: v8.9.2
Windows 10 Version: 1709, Build: 116299.125
svelte-loader Version: 2.3.2
Thank you :)
=> make the path returned by tmpdir() posix style slashes

README.md, index.js, lib/hot-api.js, package.json, test/loader.spec.js
IMHO Hot loading should be baked in here rather than relying on a separate plugin as per [svelte-hot-loader](https://github.com/ekhaled/svelte-hot-loader)
This PR is feature complete, including tests and doc updates, and is ready for review.
Below is a brief overview of how it all works.
It works by using a proxy class to wrap the actual component. Once wrapped, for all intents and purposes, the proxy masquerades as the component.
It forwards all method calls (including custom methods) to the wrapped component and references all relevant component properties.
For some methods, such as `constructor`, `_mount`, `_unmount` and `destroy`, the proxy does some additional book-keeping before forwarding the method calls.
The proxy then adds a couple of extra methods, `_register` and `_rerender` …
=> Hot loading support

index.js
Maybe I am missing something, but I think we should allow for these options to be overridden.
=> Allow for `shared` and `format` options to be overridden

index.js, lib/hot-api.js
See ekhaled/svelte-hot-loader#10 for a bit of background.
The problem was... 
While components were wrapped up in a proxy on initial load, after a hot reload only the instances were re-rendered. The wrapped component was never exported.
This works fine for nested components. But, for top-level components, it caused webpack to update its reference of the component to the unwrapped component.
When the top-level component was being mounted later on, using `new Component`, the unwrapped component was mounted.
The unwrapped component has no idea how to handle hot reloads... therefore it wasn't responding to HMR updates.
This PR fixes the immediate problem. 
But it has opened my eyes to problems that I might have to tackle in the future.
**For example:** 
When a new component comes in via hot …
=> fix for ekhaled/svelte-hot-loader#10

index.js, test/loader.spec.js
=> deprecate options.style etc

package.json
Currently there's ugly warnings in sapper because svelte-loader believes it is incompatible with sapper 2. It does not appear to be _at all_ incompatible with v2 though. Currently I'm ignoring the irritating warning.
The problem is that there are really two versions to keep track of in svelte:
1. The compiler API. (The part that matters for svelte-loader)
2. The svelte language itself. (The part that got svelte bumped to v2).
Both are interesting. Both need to be tracked. But they should probably be tracked in separate packages to allow more specific dependencies. (So, for example, you could lock into the compiler API at `^1.44.0` but the language at '2.x').
=> Allow any version of svelte greater than 1.44.0

index.js
Currently, the `import '<filePath>.js'` is unescaped in windows environments:
`'C:\project\style.svelte.css'` is treated as `C:projectstyle.svelte.css`
=> Escape virtual css file path for Windows support

lib/virtual.js
Fixes #63 
This PR makes a small refactor that checks for the presence of `compiler.hooks` before tapping in the `watch-run` hook. This is necessary to support versions of previous to [`webpack@4.0.0`](https://github.com/webpack/webpack/releases/tag/v4.0.0). When `compiler.hooks` are not available, this change will fall back to the original `compiler.plugin('watch-run', () => {});` approach that is expected for these earlier version of `webpack`.
Surely it would be nice for everybody to just update `webpack` and see the problem go away, but it just isn't always that simple in the big business world.
=> [#63] check for compiler.hooks

index.js, package-lock.json, package.json
This makes some small changes to get `svelte-loader` working with the current v3 alpha branch.
=> Get svelte-loader working with v3 alpha

index.js
Before [these changes](https://github.com/sveltejs/svelte-loader/commit/f919ccf0c9b9d3d615269f54c33ff3f3086ef1d0#diff-168726dbe96b3ce427e7fedce31bb0bcL113), when `emitCss` was `true`, the compiler option `css` was automatically set to `false`.
=> fix: 🐛 prevent css injection if emitCss is set to true

.travis.yml
Travis was running on 6, 8, and 9.  This was failing because the compiler code uses `async` in the preprocess function. This updates travis to use 8, 10, and 12.
=> update travis config to run on current Node versions

index.js
Fixes #104. We appear to have been already correctly handling the warning array returned by the compiler, but we were neglecting to remove `onwarn` from the options we passed to the compiler.
=> don't pass `onwarn` to compiler itself in Svelte 3

lib/virtual.js
If the input filesystem doesn't have purge, the current code throws.
```
C:\dev\nativescript\svelte-ns-testapp\node_modules\svelte-loader\lib\virtual.js:15
originalPurge.call(this, arguments);
^
TypeError: Cannot read property 'call' of undefined
at Object.VirtualModulesPlugin.compiler.inputFileSystem.purge (C:\dev\nativescript\svelte-ns-testapp\node_modules\svelte-loader\lib\virtual.js:15:18)
at Compiler.purgeInputFileSystem (C:\dev\nativescript\svelte-ns-testapp\node_modules\webpack\lib\Compiler.js:302:25)
at compilerCallback (C:\dev\nativescript\svelte-ns-testapp\node_modules\webpack-cli\bin\cli.js:483:15)
```
I encountered this problem. This commit solved the problem
=> Some input filesystems don't implement purge

README.md
Webpack gave me an error when I tried the hotReload example:
```
Error: options/query provided without loader (use loader + options) in {
"test": {},
"exclude": {},
"use": [
"svelte-loader"
],
"options": {
"hotReload": true
}
}
```
I've fixed it so it'll work, with `loader` and `options` inside a `use` block.
=> Fix hotReload example

lib/virtual.js
VirtualStats was missing millisecond variables and incorrectly provided time value as milliseconds, when Node provides it as Date object - https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_class_fs_stats.
This made webpack crash periodically when using cache-loader in front of svelte-loader.
=> fix: made VirtualStats compatible with Node 6/8/10/12/14

lib/virtual.js
Clarify that the compiler is the webpack compiler and not the svelte compiler
=> Add JSDoc for VirtualModulesPlugin constructor

README.md
**What?** Add install instructions.
**Why?** I wasn't paying attention when I installed the loader, and didn't realise `svelte` was a peer dependency. This should make it more clear :v:
=> Add npm install instructions to readme

.github/workflows/ci.yml, .travis.yml, test/loader.spec.js
Per https://github.com/sveltejs/svelte-loader/pull/140#pullrequestreview-514153012, most Svelte repos are using Github Actions now, so let's use it here too. travis-ci.org is shutting down soon and reducing support for OSS repos too. This also has the advantage of testing on Github Actions.
=> Move CI to Github Actions

LICENSE.md
Currently the licence name "MIT" is in the `package.json` but it there isn't an actual licence in the repo. #136 would have added a license but now #146 is the future, and that PR clears up the license issue by not including `webpack-virtual-modules` in-repo, so it doesn't have to affect the `LICENSE` file.
=> Explicitly licence under MIT

index.js
**What's the problem this PR addresses?**
If the filepath contains two dollar signs (`$$`) then the replacement here https://github.com/sveltejs/svelte-loader/blob/00e8607f25997e722d6dd6ba1e3b6977093f2f89/index.js#L49 removes one of them causing webpack to look for a path that doesn't exist
`.yarn/$$virtual/svelte-loader-virtual-ffb4749d44/2/svelte-loader/lib/hot-api.js` turns into `.yarn/$virtual/svelte-loader-virtual-ffb4749d44/2/svelte-loader/lib/hot-api.js`
**How did you fix it?**
Use the callback version of replace with uses the literal value provided
=> fix: handle path with dollar signs

index.js
We dropped Svelte 2 from the Rollup plugin. Might as well do it here too in order to simplify things
=> Drop Svelte 2 support

.github/workflows/ci.yml, CHANGELOG.md
Node 8 support was dropped from `rollup-plugin-svelte` and everywhere else. There's no reason this plugin won't work on Node 8, but as long as we're doing a major version bump we might as well drop officially supporting it so that we're not stuck with it in the future
=> Drop Node 8 support

.eslintrc, CHANGELOG.md, README.md, index.js, package-lock.json, package.json, test/loader.spec.js
This updates it to match `rollup-plugin-svelte` and also simplifies the code
=> Move compiler options under compilerOptions

README.md, index.js, lib/hot-api.js, test/loader.spec.js
Here's a branch for refactoring. I'll put some changes that I find reasonable here.
Get involved and tell me what you would want to see here.
Fixes #95, Closes #142, Closes #93, Closes #77
=> Refactor code, drop more legacy stuff

README.md
https://github.com/rixo/svelte-hmr/releases/tag/v0.12.0-0
=> Fix hotOptions documentation in readme

index.js
Inspired by this: https://github.com/sveltejs/rollup-plugin-svelte/pull/157
Fixes #171
=> Add preprocessor sourcemap

CHANGELOG.md, index.js
This repopulates sourcesContent if its empty.
Tested preprocessed and not preprocessed builds. Looks like everything is fine.
Haven't encountered anything weird like `sources[Content].length > 1` in my tests.
Thanks @rtpt-jonaslieb for the find.
Fixes #176.
=> Fix sourcesContent

CHANGELOG.md, index.js, lib/make-hot.js, package.json, test/loader.spec.js
This should resolve webpack4 support (#178 ) and pickup the latest HMR changes needed to fix Svelte Native support
=> Update to latest Svelte-HMR

index.js
We plan to release a version of `svelte-package` that encourages package authors to omit the `default` export condition. To resolve these packages, `svelte-loader` users are required to have `conditionNames: ['svelte']` in their webpack config.
With this change, we can identify cases where the field is not configured, and print a loud warning that will hopefully allow people to self-diagnose resolution failures and fix them. Once we ship docs for `svelte-package`, we could supplement this PR with a link to them.
=> warn on missing svelte condition

.github/workflows/ci.yml
Svelte 4 will be dropping support for these Node versions as well: https://github.com/sveltejs/svelte/pull/8482
=> drop support for Node 10 and Node 12

README.md
We've got it in `mainFields`, so it should be in `conditionNames` as well. This will matter for Svelte 4 (https://github.com/sveltejs/svelte/pull/8516)
=> docs: add `browser` to `conditionNames`

index.js, test/loader.spec.js
This pull request fixes a couple errors I hit when setting `{ compilerOptions: { enableSourcemap: false } }`. At different places, the loader code assumes that each of `js.map` and `css.map` are non-null. Both errors are triggered in the added tests.
(I assume that disabling sourcemaps at the Svelte level rather than through the webpack config is uncommon. In my case, I was disabling CSS sourcemaps for Svelte specifically in order to work around some issues with preprocessor map handling. I found the JS sourcemap error in the course of fixing the CSS error.)
=> fix: loader errors when sourcemaps are disabled in svelte

index.js
Fix loading the default module exports when config is ESM to suppress the warning of checking "resolve.conditionNames".
=> Interop configPath default
